### ISSUE TITLE
TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by wackerr** [elupus/hass_nibe#11]
Hi,
I get the below error. Not sure if its my fault or the code.
Thanks

 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/nibe/__init__.py", line 111, in async_setup_systems
    await asyncio.gather(*tasks)
  File "/config/custom_components/nibe/__init__.py", line 370, in load
    self.system = await self.uplink.get_system(self.system_id)
  File "/config/deps/lib/python3.6/site-packages/nibeuplink/__init__.py", line 336, in get_system
    return await self.get('systems/{}'.format(system_id))
  File "/config/deps/lib/python3.6/site-packages/nibeuplink/__init__.py", line 218, in get
    headers= {},
  File "/config/deps/lib/python3.6/site-packages/nibeuplink/__init__.py", line 232, in _request
    if 'json' in response.headers.get('CONTENT-TYPE'):
TypeError: argument of type 'NoneType' is not iterable

**Comment by elupus** [comment]
My guess is you have specified an invalid systemid

**Comment by wackerr** [comment]
In the example below configuration was system: 0.
If I set it something else, for example 2 I get this:
18-10-19 16:45:42 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/nibe/__init__.py", line 111, in async_setup_systems
    await asyncio.gather(*tasks)
  File "/config/custom_components/nibe/__init__.py", line 370, in load
    self.system = await self.uplink.get_system(self.system_id)
  File "/config/deps/lib/python3.6/site-packages/nibeuplink/__init__.py", line 336, in get_system
    return await self.get('systems/{}'.format(system_id))
  File "/config/deps/lib/python3.6/site-packages/nibeuplink/__init__.py", line 218, in get
    headers= {},
  File "/config/deps/lib/python3.6/site-packages/nibeuplink/__init__.py", line 240, in _request
    await raise_for_status(response)
  File "/config/deps/lib/python3.6/site-packages/nibeuplink/__init__.py", line 74, in raise_for_status
    headers=response.headers)
aiohttp.client_exceptions.ClientResponseError: 404, message='{
  "httpStatusCode": 404,
  "errorCode": 2,
  "timestamp": "2018-10-19T14:45:42.5385935Z",
  "details": [
    "The system was not found"
  ],
  "data": null
}'

**Comment by elupus** [comment]
You need to figure out your systems:s real Id. Originally if you only add nibe block with auth information and no systems at all it should list available systems in log. might still work.

**Comment by wackerr** [comment]
Thanks, That did the trick.
Might be worth adding that info in the readme?
