### ISSUE TITLE
Entities from 3rd system are unavailable in HA

### ISSUE THREAD

**Issue by cezarysz** [elupus/hass_nibe#113]
I have 3 heat pumps integrated in my Home Assistant.
After last updete entities from 3rd system are unavaible in my integration.
In logs: _"Setup of platform nibe is taking longer than 60 seconds. Startup will proceed without waiting any longer."_
All entities from another two systems are visible.
3rd system is visible and working fine on nibe uplink web page.

**Comment by elupus** [comment]
Strange. Do you see it if you open up the configure page for the integration in UI?

**Comment by cezarysz** [comment]
When i click "configure" on integration I can see only blank popup "Configure Systems" with "Confirm" button.
When i click "confirm" it shows error "User input malformed"

**Comment by elupus** [comment]
Do you get errors in your log?

**Comment by cezarysz** [comment]
> Do you get errors in your log?

Only few warnings like "Setup of fan platform nibe is taking over 10 seconds" and 1 occurred:

```
Source: custom_components/nibe/__init__.py:207
Integration: Nibe Uplink Heat Pumps (documentation)
First occurred: 17 listopada 2021, 22:35:36 (1 occurrences)
Last logged: 17 listopada 2021, 22:35:36

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 999, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 865, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/resolver.py", line 31, in resolve
    infos = await self._loop.getaddrinfo(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 856, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/socket.py", line 954, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/nibe/services.py", line 46, in fun
    await callable()
  File "/config/custom_components/nibe/__init__.py", line 207, in _async_refresh
    systems_raw = await uplink.get_systems()
  File "/usr/local/lib/python3.9/site-packages/nibeuplink/uplink.py", line 189, in get_systems
    data = await self.get("systems")
  File "/usr/local/lib/python3.9/site-packages/nibeuplink/uplink.py", line 82, in get
    return await self.session.request(
  File "/usr/local/lib/python3.9/site-packages/nibeuplink/session.py", line 175, in request
    response = await self.session.request(*args, auth=await self._get_auth(), **kw)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 520, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 535, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 892, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 1011, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host api.nibeuplink.com:443 ssl:default [Try again]
```

and


```
Logger: custom_components.nibe
Source: custom_components/nibe/__init__.py:338
Integration: Nibe Uplink Heat Pumps (documentation)
First occurred: 17 listopada 2021, 21:55:09 (1 occurrences)
Last logged: 17 listopada 2021, 21:55:09

Unexpected error fetching Nibe Uplink: 74509 data: 'NoneType' object has no attribute 'request'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 147, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/nibe/__init__.py", line 317, in _update
    await self.update_statuses()
  File "/config/custom_components/nibe/__init__.py", line 338, in update_statuses
    status_icons = await self.uplink.get_status(self.system_id)
  File "/usr/local/lib/python3.9/site-packages/nibeuplink/uplink.py", line 230, in get_status
    data = await self.get_status_raw(system_id)
  File "/usr/local/lib/python3.9/site-packages/nibeuplink/uplink.py", line 227, in get_status_raw
    return await self.get(f"systems/{system_id}/status/system")
  File "/usr/local/lib/python3.9/site-packages/nibeuplink/uplink.py", line 82, in get
    return await self.session.request(
  File "/usr/local/lib/python3.9/site-packages/nibeuplink/session.py", line 175, in request
    response = await self.session.request(*args, auth=await self._get_auth(), **kw)
AttributeError: 'NoneType' object has no attribute 'request'
```

**Comment by elupus** [comment]
Your DNS lookups seem to be failing on your network. So you seem to be having issues  with the connections to nibes servers.

**Comment by cezarysz** [comment]
> Your DNS lookups seem to be failing on your network. So you seem to be having issues with the connections to nibes servers.

Why only entities from 3rd system does not work? All entities from first 2 system are working fine all the time.

**Comment by elupus** [comment]
It's loaded at startup. If it errors then, it won't load anything later.

**Comment by elupus** [comment]
Restart Hass. Then check configure of integration again. It should list all three.

**Comment by cezarysz** [comment]
> Restart Hass. Then check configure of integration again. It should list all three.

After host reboot problem remains.
Same problem with "Configure" button as I mention before.
When I try to "Reload" integration from UI I can see that all entities are unavailable then after some time entities from 1st system are appears, then from 2nd system, but then procedure seems stop and every entity from 3rd system remains unavailable.

**Comment by elupus** [comment]
Similar errors in log?

**Comment by cezarysz** [comment]
> Similar errors in log?

Exactly the same.

**Comment by elupus** [comment]
Sound unlikely that you get the exact same errors with DNS lookups. Can you post a full log?

**Comment by cezarysz** [comment]
> Sound unlikely that you get the exact same errors with DNS lookups. Can you post a full log?
You mean full log from HA Core from start? Without grep to "nibe"?

**Comment by elupus** [comment]
Yeah, if you prefer you can pm me on discord and share it there if you don't want it public here.

Please add this to logger 

`nibeuplink: debug`
`custom_components.nibe: debug`

https://www.home-assistant.io/integrations/logger/

**Comment by cezarysz** [comment]
[home-assistant.log](https://github.com/elupus/hass_nibe/files/7565745/home-assistant.log)

Systems 45862 and 74509 are fine.
There's problem with system: 130489

**Comment by elupus** [comment]
I think you system is a bit overloaded :). Anyway i did find a bug in the system selection dialog. Could you update and try again? I suspect you have some old data in your config entry from an older nibe version that causes it to only select the systems you had back then.

**Comment by cezarysz** [comment]
> I think you system is a bit overloaded :).

Yes. A little bit :) 
> 
> Anyway i did find a bug in the system selection dialog. Could you update and try again? I suspect you have some old data in your config entry from an older nibe version that causes it to only select the systems you had back then.

Now it's better, but still doesn't work.
Now I can see system list after use "configure" button in UI. 
3rd system is unchecked. When i'm trying to add him to configuration it says "success" but after click "configure" Once again this system is still unchecked. Entities are still unavailable.

**Comment by elupus** [comment]
Sigh. I've mixed up config and options. Will fix a bit later.

**Comment by elupus** [comment]
Update and try again.

**Comment by cezarysz** [comment]
> Update and try again.

Yeah. Now it's fine! Thanks mate!
