### ISSUE TITLE
Nibe Uplink setup - unexpected keyword argument 'configuration_url'

### ISSUE THREAD

**Issue by twlodar** [elupus/hass_nibe#114]
Hi 
I've been using Nibe integration for months but about ten days ago it crashed.
I checked [(https://github.com/elupus/hass_nibe)] and decided to remove old integration and setup it from the scratch.
But after successful authentication at nibeuplinks home page it stops resulting an error as below.

Logger: homeassistant.config_entries
Source: custom_components/nibe/__init__.py:313
Integration: Nibe Uplink Heat Pumps (documentation)
First occurred: 01:46:54 (1 occurrences)
Last logged: 01:46:54
Error setting up entry for nibe

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 304, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/nibe/__init__.py", line 226, in async_setup_entry
    await _async_refresh()
  File "/config/custom_components/nibe/__init__.py", line 224, in _async_refresh
    await _async_add_system(system_raw, _get_system_config(hass, system_id))
  File "/config/custom_components/nibe/__init__.py", line 203, in _async_add_system
    await system.load()
  File "/config/custom_components/nibe/__init__.py", line 313, in load
    device_registry.async_get_or_create(
TypeError: async_get_or_create() got an unexpected keyword argument 'configuration_url'
  
Any hints?

Thanks in advance :)

**Comment by elupus** [comment]
Get a newer home assistant.

**Comment by twlodar** [comment]
Problem solved, Thx
