### ISSUE TITLE
Some temperature sensors not updating any more

### ISSUE THREAD

**Issue by priiduonu** [elupus/hass_nibe#116]
Home Assistant 2021.11.5
hass_nibe 1.2.3

It seems some sensors are not updated any more, namely:

**outdoor temp:**
Designation: BT1
Parameter ID: 40004

**hot water top:**
Designation: BT7
Parameter ID: 40013

Comparing with NIBE Uplink status page.

These sensors are updated to correct readings only after restarting HA. No further updates.

Happened somewhere between last upgrades of either HA or hass_nibe, can not trace exact moment.

At the same time other NIBE temperature sensors and all other NIBE sensors are updated normally.

No log messages.

**Comment by elupus** [comment]
Are they manually added parameters?

**Comment by priiduonu** [comment]
I do not know :-) How could I verify that? The sensor names are as follows:

```
sensor.nibe_XXXXX_40004
sensor.nibe_XXXXX_40013
```

(where XXXXX is the system ID)

When looking from the Integrations page, they both seem to be related to `F1255-12 R - XXXXX : master : status` device.

**Comment by elupus** [comment]
If manually added them to your yaml config.

**Comment by priiduonu** [comment]
No sensors in *yaml files.

**Comment by priiduonu** [comment]
Tried to reinstall hass_nibe. No changes, the above sensors still not updating.

Turned on logging, this is what I get (system_id replaced by XXXXX):

```
Dec  5 01:35:14 hal hass[11741]: 2021-12-05 01:35:14 DEBUG (MainThread) [nibeuplink.uplink] Requesting systems
Dec  5 01:35:15 hal hass[11741]: 2021-12-05 01:35:15 DEBUG (MainThread) [nibeuplink.uplink] Requesting notifications on system XXXXX
Dec  5 01:35:15 hal hass[11741]: 2021-12-05 01:35:15 DEBUG (MainThread) [nibeuplink.uplink] Delaying request by 4.499091 seconds due to throttle
Dec  5 01:35:19 hal hass[11741]: 2021-12-05 01:35:19 DEBUG (MainThread) [nibeuplink.uplink] Requesting status on system XXXXX
Dec  5 01:35:19 hal hass[11741]: 2021-12-05 01:35:19 DEBUG (MainThread) [nibeuplink.uplink] Delaying request by 4.499145 seconds due to throttle
Dec  5 01:35:24 hal hass[11741]: 2021-12-05 01:35:24 DEBUG (MainThread) [custom_components.nibe] Statuses: {'Heating', 'Brine Pump', 'Price Of Electricity', 'Heating Medium Pump', 'Compressor'}
Dec  5 01:35:24 hal hass[11741]: 2021-12-05 01:35:24 DEBUG (MainThread) [custom_components.nibe] Finished fetching Nibe Uplink: XXXXX data in 9.364 seconds (success: True)
```

**Comment by elupus** [comment]
Any errors in you log when Hass is starting up. It would be good with a complete log on startup. Running at least until you see another sensor changed twice.

**Comment by priiduonu** [comment]
Meanwhile switched back to 1.1.1 and everything works as intended!

Originally upgraded from 1.1.1 straight to 1.2.3.

Now upgraded to 1.2.0 and lots of similar messages appear on startup:

```
Dec  5 10:34:48 hal hass[11741]: 2021-12-05 10:34:48 ERROR (MainThread) [homeassistant.components.sensor] Error adding entities for domain sensor with platform nibe
Dec  5 10:34:48 hal hass[11741]: Traceback (most recent call last):
Dec  5 10:34:48 hal hass[11741]:   File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
Dec  5 10:34:48 hal hass[11741]:     await asyncio.gather(*tasks)
Dec  5 10:34:48 hal hass[11741]:   File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/entity_platform.py", line 607, in _async_add_entity
Dec  5 10:34:48 hal hass[11741]:     await entity.add_to_platform_finish()
Dec  5 10:34:48 hal hass[11741]:   File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/entity.py", line 714, in add_to_platform_finish
Dec  5 10:34:48 hal hass[11741]:     await self.async_added_to_hass()
Dec  5 10:34:48 hal hass[11741]:   File "/home/homeassistant/.homeassistant/custom_components/nibe/entity.py", line 119, in async_added_to_hass
Dec  5 10:34:48 hal hass[11741]:     self.async_on_remove(self._system.add_parameter_subscriber(self._parameters))
Dec  5 10:34:48 hal hass[11741]:   File "/home/homeassistant/.homeassistant/custom_components/nibe/__init__.py", line 389, in add_parameter_subscriber
Dec  5 10:34:48 hal hass[11741]:     parameters_clean = cast(set[ParameterId], (parameters - {None}))
Dec  5 10:34:48 hal hass[11741]: TypeError: 'type' object is not subscriptable
```

**Comment by elupus** [comment]
Those errors would case an issue. But i need you to check latest release.

**Comment by elupus** [comment]
Also what version of python are you running?

**Comment by elupus** [comment]
I actually think your issue stems from python 3.8. it's deprecated for support in home assistant anyway, so i suggest you get yourself to python 3.9.

**Comment by priiduonu** [comment]
Here is the log with latest 1.2.3:

```
Dec  5 11:12:35 hal hass[11741]: 2021-12-05 11:12:35 ERROR (MainThread) [homeassistant.components.sensor] Error adding entities for domain sensor with platform nibe
Dec  5 11:12:35 hal hass[11741]: Traceback (most recent call last):
Dec  5 11:12:35 hal hass[11741]:   File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
Dec  5 11:12:35 hal hass[11741]:     await asyncio.gather(*tasks)
Dec  5 11:12:35 hal hass[11741]:   File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/entity_platform.py", line 607, in _async_add_entity
Dec  5 11:12:35 hal hass[11741]:     await entity.add_to_platform_finish()
Dec  5 11:12:35 hal hass[11741]:   File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/entity.py", line 714, in add_to_platform_finish
Dec  5 11:12:35 hal hass[11741]:     await self.async_added_to_hass()
Dec  5 11:12:35 hal hass[11741]:   File "/home/homeassistant/.homeassistant/custom_components/nibe/entity.py", line 120, in async_added_to_hass
Dec  5 11:12:35 hal hass[11741]:     self.async_on_remove(self._system.add_parameter_subscriber(self._parameters))
Dec  5 11:12:35 hal hass[11741]:   File "/home/homeassistant/.homeassistant/custom_components/nibe/__init__.py", line 401, in add_parameter_subscriber
Dec  5 11:12:35 hal hass[11741]:     parameters_clean = cast(set[ParameterId], (parameters - {None}))
Dec  5 11:12:35 hal hass[11741]: TypeError: 'type' object is not subscriptable
```
[snip]
```
Dec  5 11:12:45 hal hass[11741]: 2021-12-05 11:12:45 ERROR (MainThread) [homeassistant.components.climate] Error while setting up nibe platform for climate
Dec  5 11:12:45 hal hass[11741]: Traceback (most recent call last):
Dec  5 11:12:45 hal hass[11741]:   File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/entity_platform.py", line 257, in _async_setup_platform
Dec  5 11:12:45 hal hass[11741]:     await asyncio.gather(*pending)
Dec  5 11:12:45 hal hass[11741]:   File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
Dec  5 11:12:45 hal hass[11741]:     await asyncio.gather(*tasks)
Dec  5 11:12:45 hal hass[11741]:   File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/entity_platform.py", line 607, in _async_add_entity
Dec  5 11:12:45 hal hass[11741]:     await entity.add_to_platform_finish()
Dec  5 11:12:45 hal hass[11741]:   File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/entity.py", line 714, in add_to_platform_finish
Dec  5 11:12:45 hal hass[11741]:     await self.async_added_to_hass()
Dec  5 11:12:45 hal hass[11741]:   File "/home/homeassistant/.homeassistant/custom_components/nibe/entity.py", line 120, in async_added_to_hass
Dec  5 11:12:45 hal hass[11741]:     self.async_on_remove(self._system.add_parameter_subscriber(self._parameters))
Dec  5 11:12:45 hal hass[11741]:   File "/home/homeassistant/.homeassistant/custom_components/nibe/__init__.py", line 401, in add_parameter_subscriber
Dec  5 11:12:45 hal hass[11741]:     parameters_clean = cast(set[ParameterId], (parameters - {None}))
Dec  5 11:12:45 hal hass[11741]: TypeError: 'type' object is not subscriptable
Dec  5 11:12:45 hal hass[11741]: 2021-12-05 11:12:45 ERROR (MainThread) [homeassistant.components.fan] Error adding entities for domain fan with platform nibe
Dec  5 11:12:45 hal hass[11741]: Traceback (most recent call last):
Dec  5 11:12:45 hal hass[11741]:   File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
Dec  5 11:12:45 hal hass[11741]:     await asyncio.gather(*tasks)
Dec  5 11:12:45 hal hass[11741]:   File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/entity_platform.py", line 607, in _async_add_entity
Dec  5 11:12:45 hal hass[11741]:     await entity.add_to_platform_finish()
Dec  5 11:12:45 hal hass[11741]:   File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/entity.py", line 714, in add_to_platform_finish
Dec  5 11:12:45 hal hass[11741]:     await self.async_added_to_hass()
Dec  5 11:12:45 hal hass[11741]:   File "/home/homeassistant/.homeassistant/custom_components/nibe/entity.py", line 120, in async_added_to_hass
Dec  5 11:12:45 hal hass[11741]:     self.async_on_remove(self._system.add_parameter_subscriber(self._parameters))
Dec  5 11:12:45 hal hass[11741]:   File "/home/homeassistant/.homeassistant/custom_components/nibe/__init__.py", line 401, in add_parameter_subscriber
Dec  5 11:12:45 hal hass[11741]:     parameters_clean = cast(set[ParameterId], (parameters - {None}))
Dec  5 11:12:45 hal hass[11741]: TypeError: 'type' object is not subscriptable
Dec  5 11:12:45 hal hass[11741]: 2021-12-05 11:12:45 ERROR (MainThread) [homeassistant.components.water_heater] Error adding entities for domain water_heater with platform nibe
Dec  5 11:12:45 hal hass[11741]: Traceback (most recent call last):
Dec  5 11:12:45 hal hass[11741]:   File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
Dec  5 11:12:45 hal hass[11741]:     await asyncio.gather(*tasks)
Dec  5 11:12:45 hal hass[11741]:   File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/entity_platform.py", line 607, in _async_add_entity
Dec  5 11:12:45 hal hass[11741]:     await entity.add_to_platform_finish()
Dec  5 11:12:45 hal hass[11741]:   File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/entity.py", line 714, in add_to_platform_finish
Dec  5 11:12:45 hal hass[11741]:     await self.async_added_to_hass()
Dec  5 11:12:45 hal hass[11741]:   File "/home/homeassistant/.homeassistant/custom_components/nibe/entity.py", line 120, in async_added_to_hass
Dec  5 11:12:45 hal hass[11741]:     self.async_on_remove(self._system.add_parameter_subscriber(self._parameters))
Dec  5 11:12:45 hal hass[11741]:   File "/home/homeassistant/.homeassistant/custom_components/nibe/__init__.py", line 401, in add_parameter_subscriber
Dec  5 11:12:45 hal hass[11741]:     parameters_clean = cast(set[ParameterId], (parameters - {None}))
Dec  5 11:12:45 hal hass[11741]: TypeError: 'type' object is not subscriptable
Dec  5 11:12:45 hal hass[11741]: 2021-12-05 11:12:45 ERROR (MainThread) [homeassistant.components.fan] Error while setting up nibe platform for fan
Dec  5 11:12:45 hal hass[11741]: Traceback (most recent call last):
Dec  5 11:12:45 hal hass[11741]:   File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/entity_platform.py", line 257, in _async_setup_platform
Dec  5 11:12:45 hal hass[11741]:     await asyncio.gather(*pending)
Dec  5 11:12:45 hal hass[11741]:   File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
Dec  5 11:12:45 hal hass[11741]:     await asyncio.gather(*tasks)
Dec  5 11:12:45 hal hass[11741]:   File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/entity_platform.py", line 607, in _async_add_entity
Dec  5 11:12:45 hal hass[11741]:     await entity.add_to_platform_finish()
Dec  5 11:12:45 hal hass[11741]:   File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/entity.py", line 714, in add_to_platform_finish
Dec  5 11:12:45 hal hass[11741]:     await self.async_added_to_hass()
Dec  5 11:12:45 hal hass[11741]:   File "/home/homeassistant/.homeassistant/custom_components/nibe/entity.py", line 120, in async_added_to_hass
Dec  5 11:12:45 hal hass[11741]:     self.async_on_remove(self._system.add_parameter_subscriber(self._parameters))
Dec  5 11:12:45 hal hass[11741]:   File "/home/homeassistant/.homeassistant/custom_components/nibe/__init__.py", line 401, in add_parameter_subscriber
Dec  5 11:12:45 hal hass[11741]:     parameters_clean = cast(set[ParameterId], (parameters - {None}))
Dec  5 11:12:45 hal hass[11741]: TypeError: 'type' object is not subscriptable
Dec  5 11:12:45 hal hass[11741]: 2021-12-05 11:12:45 ERROR (MainThread) [homeassistant.components.water_heater] Error while setting up nibe platform for water_heater
Dec  5 11:12:45 hal hass[11741]: Traceback (most recent call last):
Dec  5 11:12:45 hal hass[11741]:   File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/entity_platform.py", line 257, in _async_setup_platform
Dec  5 11:12:45 hal hass[11741]:     await asyncio.gather(*pending)
Dec  5 11:12:45 hal hass[11741]:   File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
Dec  5 11:12:45 hal hass[11741]:     await asyncio.gather(*tasks)
Dec  5 11:12:45 hal hass[11741]:   File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/entity_platform.py", line 607, in _async_add_entity
Dec  5 11:12:45 hal hass[11741]:     await entity.add_to_platform_finish()
Dec  5 11:12:45 hal hass[11741]:   File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/entity.py", line 714, in add_to_platform_finish
Dec  5 11:12:45 hal hass[11741]:     await self.async_added_to_hass()
Dec  5 11:12:45 hal hass[11741]:   File "/home/homeassistant/.homeassistant/custom_components/nibe/entity.py", line 120, in async_added_to_hass
Dec  5 11:12:45 hal hass[11741]:     self.async_on_remove(self._system.add_parameter_subscriber(self._parameters))
Dec  5 11:12:45 hal hass[11741]:   File "/home/homeassistant/.homeassistant/custom_components/nibe/__init__.py", line 401, in add_parameter_subscriber
Dec  5 11:12:45 hal hass[11741]:     parameters_clean = cast(set[ParameterId], (parameters - {None}))
Dec  5 11:12:45 hal hass[11741]: TypeError: 'type' object is not subscriptable
```
Will try to upgrade to python 3.9 next.

**Comment by elupus** [comment]
I suggest you do anyway, but... I put out a fix that should solve your issue. 1.2.4.

**Comment by priiduonu** [comment]
Great, seems to work as intended! Thank You very much!
