### ISSUE TITLE
Seems like Nibe have done some changes in Uplink

### ISSUE THREAD

**Issue by greberg** [elupus/hass_nibe#12]
Can't get Nibe uplink to work in Homeassistant. Have not changed anything in the config but now I get this error in my logs (debug doesn't show anything more):

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/nibe/__init__.py", line 111, in async_setup_systems
    await asyncio.gather(*tasks)
  File "/config/custom_components/nibe/__init__.py", line 373, in load
    await self.load_unit(unit)
  File "/config/custom_components/nibe/__init__.py", line 328, in load_unit
    unit.get(CONF_CATEGORIES)))
  File "/config/custom_components/nibe/__init__.py", line 256, in load_categories
    return await asyncio.gather(*tasks)
  File "/config/custom_components/nibe/__init__.py", line 228, in load_parameter_group
    sensors)
  File "/config/custom_components/nibe/__init__.py", line 210, in load_sensor
    return await self.load_platform(discovery_info, 'sensor')
  File "/config/custom_components/nibe/__init__.py", line 186, in load_platform
    load_info)
TypeError: async_load_platform() missing 1 required positional argument: 'hass_config'

###################Configuration.yaml#############
nibe:
  client_id: secret
  client_secret: secret
  redirect_uri: "url back to my instace/api/nibe/auth"
  writeaccess: false # set to true to support climate write (needs new tokens)
  systems:
      - system: 24887
        units:
          - unit: 0
            categories:

**Comment by elupus** [comment]
Nah its new home assistant causing problems.

**Comment by greberg** [comment]
Hmm good. Do you know what is causing it? New authentication process?

**Comment by elupus** [comment]
Internal API change

**Comment by basn** [comment]
Aahh, this explains why i didnt get a temp reading :)

**Comment by elupus** [comment]
fixed i think

**Comment by greberg** [comment]
Confirmed! It works

Thanks Joakim

**Comment by basn** [comment]
Yup works here to! awesome!
