### ISSUE TITLE
Issue AttributeError: 'list' object has no attribute 'split'

### ISSUE THREAD

**Issue by vaclaj** [elupus/hass_nibe#123]
Hello, I'm very new here, trying to read values from my heatpump. I was able to install your modul to my RPI running python3.
When I'm trying to run your script, following error will appear. Can you help me what can be wrong:

pi@raspberrypi:~ $ python3 .local/bin/nibeuplink --client_id xxxxxxx --client_secret yyyyyyyy --redirect_uri https://www.marshflattsfarm.org.uk/nibeuplink/oauth2callback/index.php --verbose
2022-01-16 19:29:59,648 - asyncio - DEBUG - Using selector: EpollSelector
Traceback (most recent call last):
  File ".local/bin/nibeuplink", line 10, in <module>
    sys.exit(main())
  File "/home/pi/.local/lib/python3.7/site-packages/nibeuplink/__main__.py", line 186, in main
    loop.run_until_complete(run())
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/home/pi/.local/lib/python3.7/site-packages/nibeuplink/__main__.py", line 84, in run
    scope=scope,
  File "/home/pi/.local/lib/python3.7/site-packages/nibeuplink/session.py", line 63, in __init__
    if set(scope).issubset(set(access_data["scope"].split(" "))):
AttributeError: 'list' object has no attribute 'split'

**Comment by vaclaj** [comment]
sorry wrong topic move to nibeuplink
