### ISSUE TITLE
entity_category must be a valid EntityCategory instance

### ISSUE THREAD

**Issue by matlimatli** [elupus/hass_nibe#131]
When starting Home Assistant (2022.4.0), I get a lot of these messages in the log:

```2022-04-06 22:50:32 ERROR (MainThread) [homeassistant.components.sensor] Error adding entities for domain sensor with platform nibe
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 510, in _async_add_entity
    entry = entity_registry.async_get_or_create(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 345, in async_get_or_create
    return self.async_update_entity(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 529, in async_update_entity
    raise ValueError("entity_category must be a valid EntityCategory instance")
ValueError: entity_category must be a valid EntityCategory instance```

It seems we should now use the EntityCategory class. I'll try to submit a PR.

**Comment by matlimatli** [comment]
See also https://github.com/home-assistant/core/pull/69015
