### ISSUE TITLE
Initial installation fails.

### ISSUE THREAD

**Issue by AndersHoglund** [elupus/hass_nibe#139]
Trying to get the NIBE Uplink integration installed. Everything flows nicely until Nibe wants to open the API callback page "http://192.168.x.y:8123/api/nibe/auth?code=hUxK....." . This only shows new a blank page, nothing. On the HA integration setup page I am stuck with a popup, saying "Authorize home assistant for Nibe, .... Open Website" Pushing "Open Website" leads back to Nibe Uplink authorization page again and back to another local blank api callback page. On the main HA setup page, the popup is still open.
HA 2022Log has a few entries, see below. I did copy & paste complete identifier and secret from Uplink, still "incorrect client secret" in the logs. 

Using HA in a VMware container on Ubuntu.
    Home Assistant 2022.8.0 
    Supervisor 2022.07.0 
    Operating System 8.4 
    Frontend 20220802.0 - latest 
```
2022-08-04 13:38:51.333 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration nibe which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-08-04 13:44:46.390 ERROR (MainThread) [custom_components.nibe.config_flow] Error on converting code
aiohttp.client_exceptions.ClientResponseError: 401, message="{'error': 'invalid_client', 'error_description': 'The client secret was incorrect.'}", url=URL('https://api.nibeuplink.com/oauth/token')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/nibe/config_flow.py", line 114, in async_step_auth
    await self.session.get_access_token(user_input["code"])
  File "/usr/local/lib/python3.10/site-packages/nibeuplink/session.py", line 128, in get_access_token
    await raise_for_status(response)
  File "/usr/local/lib/python3.10/site-packages/nibeuplink/session.py", line 26, in raise_for_status
    raise UplinkResponseException(data.get("errorCode"), data) from e
nibeuplink.exceptions.UplinkResponseException: UNKNOWN_CODE: Unknown error None
{'error': 'invalid_client', 'error_description': 'The client secret was incorrect.'}
2022-08-04 13:45:12.351 ERROR (MainThread) [custom_components.nibe.config_flow] Error on converting code
aiohttp.client_exceptions.ClientResponseError: 401, message="{'error': 'invalid_client', 'error_description': 'The client secret was incorrect.'}", url=URL('https://api.nibeuplink.com/oauth/token')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/nibe/config_flow.py", line 114, in async_step_auth
    await self.session.get_access_token(user_input["code"])
  File "/usr/local/lib/python3.10/site-packages/nibeuplink/session.py", line 128, in get_access_token
    await raise_for_status(response)
  File "/usr/local/lib/python3.10/site-packages/nibeuplink/session.py", line 26, in raise_for_status
    raise UplinkResponseException(data.get("errorCode"), data) from e
nibeuplink.exceptions.UplinkResponseException: UNKNOWN_CODE: Unknown error None
{'error': 'invalid_client', 'error_description': 'The client secret was incorrect.'}
2022-08-04 13:46:11.444 ERROR (MainThread) [custom_components.nibe.config_flow] Error on converting code
aiohttp.client_exceptions.ClientResponseError: 400, message="{'error': 'invalid_request'}", url=URL('https://api.nibeuplink.com/oauth/token')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/nibe/config_flow.py", line 114, in async_step_auth
    await self.session.get_access_token(user_input["code"])
  File "/usr/local/lib/python3.10/site-packages/nibeuplink/session.py", line 128, in get_access_token
    await raise_for_status(response)
  File "/usr/local/lib/python3.10/site-packages/nibeuplink/session.py", line 26, in raise_for_status
    raise UplinkResponseException(data.get("errorCode"), data) from e
nibeuplink.exceptions.UplinkResponseException: UNKNOWN_CODE: Unknown error None
{'error': 'invalid_request'}
2022-08-04 13:50:53.006 ERROR (MainThread) [homeassistant] Error doing job: Unclosed client session

```

**Comment by vahem2lu** [comment]
Had the same problem. Maybe suggestion to edit error message after API access grant from Nibe.
So if the authentication fails after API grant has been given, then software should say it in the GUI.
