### ISSUE TITLE
HA 2024.1 issues, deprecated constant which will be removed in HA Core 2025.1 and water_heater TypeError: argument of type 'int' is not iterable

### ISSUE THREAD

**Issue by hossihub** [elupus/hass_nibe#199]
Upgraded Home Assistant docker container to 2024.1.0 and the following issues were found in the log at startup.

2024-01-05 00:21:39.132 WARNING (MainThread) [homeassistant.const] TEMP_CELSIUS was used from nibe, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead, please report it to the author of the 'nibe' custom integration
2024-01-05 00:21:39.162 WARNING (MainThread) [homeassistant.components.water_heater] SUPPORT_OPERATION_MODE was used from nibe, this is a deprecated constant which will be removed in HA Core 2025.1. Use WaterHeaterEntityFeature.OPERATION_MODE instead, please report it to the author of the 'nibe' custom integration
2024-01-05 00:21:39.172 WARNING (MainThread) [homeassistant.components.water_heater] SUPPORT_OPERATION_MODE was used from nibe, this is a deprecated constant which will be removed in HA Core 2025.1. Use WaterHeaterEntityFeature.OPERATION_MODE instead, please report it to the author of the 'nibe' custom integration
2024-01-05 00:21:39.180 WARNING (MainThread) [homeassistant.const] TEMP_CELSIUS was used from nibe, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead, please report it to the author of the 'nibe' custom integration
2024-01-05 00:21:46.145 WARNING (MainThread) [homeassistant.const] ELECTRIC_CURRENT_AMPERE was used from nibe, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfElectricCurrent.AMPERE instead, please report it to the author of the 'nibe' custom integration
2024-01-05 00:21:46.153 WARNING (MainThread) [homeassistant.const] ELECTRIC_CURRENT_MILLIAMPERE was used from nibe, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfElectricCurrent.MILLIAMPERE instead, please report it to the author of the 'nibe' custom integration
2024-01-05 00:21:46.162 WARNING (MainThread) [homeassistant.const] ELECTRIC_POTENTIAL_MILLIVOLT was used from nibe, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfElectricPotential.MILLIVOLT instead, please report it to the author of the 'nibe' custom integration
2024-01-05 00:21:46.170 WARNING (MainThread) [homeassistant.const] ELECTRIC_POTENTIAL_VOLT was used from nibe, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfElectricPotential.VOLT instead, please report it to the author of the 'nibe' custom integration
2024-01-05 00:21:46.179 WARNING (MainThread) [homeassistant.const] ENERGY_KILO_WATT_HOUR was used from nibe, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfEnergy.KILO_WATT_HOUR instead, please report it to the author of the 'nibe' custom integration
2024-01-05 00:21:46.188 WARNING (MainThread) [homeassistant.const] ENERGY_MEGA_WATT_HOUR was used from nibe, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfEnergy.MEGA_WATT_HOUR instead, please report it to the author of the 'nibe' custom integration
2024-01-05 00:21:46.197 WARNING (MainThread) [homeassistant.const] ENERGY_WATT_HOUR was used from nibe, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfEnergy.WATT_HOUR instead, please report it to the author of the 'nibe' custom integration
2024-01-05 00:21:46.205 WARNING (MainThread) [homeassistant.const] TEMP_CELSIUS was used from nibe, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead, please report it to the author of the 'nibe' custom integration
2024-01-05 00:21:46.214 WARNING (MainThread) [homeassistant.const] TEMP_FAHRENHEIT was used from nibe, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.FAHRENHEIT instead, please report it to the author of the 'nibe' custom integration
2024-01-05 00:21:46.222 WARNING (MainThread) [homeassistant.const] TEMP_KELVIN was used from nibe, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.KELVIN instead, please report it to the author of the 'nibe' custom integration
2024-01-05 00:21:46.231 WARNING (MainThread) [homeassistant.const] TIME_HOURS was used from nibe, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTime.HOURS instead, please report it to the author of the 'nibe' custom integration
2024-01-05 00:22:04.521 ERROR (MainThread) [homeassistant.components.water_heater] Error adding entities for domain water_heater with platform nibe
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 662, in _async_add_entity
    capabilities=entity.capability_attributes,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/water_heater/__init__.py", line 244, in capability_attributes
    if WaterHeaterEntityFeature.OPERATION_MODE in self.supported_features:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'int' is not iterable

**Comment by hossihub** [comment]
seems fixed in 1.6.1
