### ISSUE TITLE
Invalid config, HA 0.52.1

### ISSUE THREAD

**Issue by zdmh100** [elupus/hass_nibe#2]
Hi, thanks for posting this excellent project.
I get an 'invalid config' message when I try to run the Nibe plugin.
HA 0.52.1 running on an Raspberry 3, Nibe VVM 325 f/w 8114R2.
Downloaded latest plugin here today.

This is what I get from the log:

2017-09-05 22:48:24 ERROR (MainThread) [homeassistant.setup] Error during setup of component nibe
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/homeassistant/setup.py", line 194, in _async_setup_component
    component.setup, hass, processed_config)
  File "/usr/lib/python3.6/asyncio/futures.py", line 331, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.6/asyncio/tasks.py", line 244, in _wakeup
    future.result()
  File "/usr/lib/python3.6/asyncio/futures.py", line 244, in result
    raise self._exception
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/nibe.py", line 86, in setup
    hass.data[DOMAIN] = NibeUplink(hass, config)
  File "/config/custom_components/nibe.py", line 152, in __init__
    submit_caption = 'Set Url'
  File "/usr/lib/python3.6/site-packages/homeassistant/components/configurator.py", line 78, in request_config
    hass.loop, ft.partial(async_request_config, hass, *args, **kwargs)
AttributeError: 'str' object has no attribute 'loop'
2017-09-05 22:48:25 WARNING (MainThread) [homeassistant.setup] Setup of tts is taking over 10 seconds.
2017-09-05 22:49:10 WARNING (MainThread) [homeassistant.components.media_player] Setup of platform cast is taking over 10 seconds.
2017-09-05 22:49:12 WARNING (MainThread) [homeassistant.components.media_player] Setup of platform cast is taking over 10 seconds.
2017-09-05 22:49:13 WARNING (MainThread) [homeassistant.components.media_player] Setup of platform cast is taking over 10 seconds.
2017-09-05 23:38:59 WARNING (MainThread) [homeassistant.helpers.entity] Update of media_player.samsung_7_series_60_ue60ks7005 is taking over 10 seconds
2017-09-05 23:39:00 WARNING (MainThread) [homeassistant.components.media_player] Updating samsungtv media_player took longer than the scheduled update interval 0:00:10

**Comment by freddanastrom** [comment]
More or less the same issue for me with HA 0.53.0

2017-09-09 19:42:22 ERROR (MainThread) [homeassistant.setup] Error during setup of component nibe Traceback (most recent call last): File "/srv/homeassistant/homeassistant_venv/lib/python3.4/site-packages/homeassistant/setup.py", line 194, in _async_setup_component component.setup, hass, processed_config) File "/usr/lib/python3.4/asyncio/futures.py", line 388, in __iter__ yield self # This tells Task to wait for completion. File "/usr/lib/python3.4/asyncio/tasks.py", line 286, in _wakeup value = future.result() File "/usr/lib/python3.4/asyncio/futures.py", line 277, in result raise self._exception File "/usr/lib/python3.4/concurrent/futures/thread.py", line 54, in run result = self.fn(*self.args, **self.kwargs) File "/home/homeassistant/.homeassistant/custom_components/nibe.py", line 86, in setup hass.data[DOMAIN] = NibeUplink(hass, config) File "/home/homeassistant/.homeassistant/custom_components/nibe.py", line 152, in __init__ submit_caption = 'Set Url' File "/srv/homeassistant/homeassistant_venv/lib/python3.4/site-packages/homeassistant/components/configurator.py", line 79, in request_config ).result() AttributeError: 'str' object has no attribute 'loop'

**Comment by elupus** [comment]
Seems i might have forgotten till push some commits. Will look at it.

**Comment by elupus** [comment]
Please try master now.

**Comment by freddanastrom** [comment]
Thanks! Everything is up and running 👍

**Comment by zdmh100** [comment]
Got there as well. Thanks!
