### ISSUE TITLE
The following components and platforms could not be set up: nibe.climate

### ISSUE THREAD

**Issue by desertspider** [elupus/hass_nibe#21]
Just downloaded the new Nibe component.

Evrything works just fine, but got the following error:

System is Windows 10 with hass 0.88.1

`2019-03-05 14:07:14 ERROR (MainThread) [homeassistant.loader] Error loading custom_components.nibe.climate. Make sure all dependencies are installed
Traceback (most recent call last):
  File "c:\users\sjoerd\appdata\local\programs\python\python36-32\lib\site-packages\homeassistant\loader.py", line 147, in _load_file
    module = importlib.import_module(path)
  File "c:\users\sjoerd\appdata\local\programs\python\python36-32\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Sjoerd\AppData\Roaming\.homeassistant\custom_components\nibe\climate.py", line 10, in <module>
    from homeassistant.components.climate.const import (ATTR_OPERATION_MODE,
ImportError: cannot import name 'STATE_AUTO'
2019-03-05 14:07:14 ERROR (MainThread) [homeassistant.loader] Unable to find platform nibe
2019-03-05 14:07:14 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform nibe.climate: Platform not found.`

Config:
`
nibe:
    client_id: xxxxx
    client_secret: xxx
    redirect_uri: http://192.168.0.152:8123/api/nibe/auth
    writeaccess: false
``
    systems:
        - system: 65530
          units:
            - unit: 0
              categories:
              statuses:
            - unit: 1
              categories:
              statuses:
          climates: false
          water_heaters: false
`

**Comment by elupus** [comment]
Oh crap. Did I remove fallback code one homeassistant version too soon.

**Comment by elupus** [comment]
Just hold of for 0.89.

**Comment by desertspider** [comment]
Ok, will do that.

**Comment by desertspider** [comment]
No more error's in 0.89.0. Closing. thnx!
