### ISSUE TITLE
Error during setup of component nibe

### ISSUE THREAD

**Issue by ChristophLindemann** [elupus/hass_nibe#22]
During initialization of HA I get the following

```
019-03-06 00:30:16 ERROR (MainThread) [homeassistant.setup] Error during setup of component nibe
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/setup.py", line 151, in _async_setup_component
    hass, processed_config)
  File "/config/custom_components/nibe/__init__.py", line 186, in async_setup
    await async_register_services(hass)
  File "/config/custom_components/nibe/__init__.py", line 128, in async_register_services
    from nibeuplink import SMARTHOME_MODES
ModuleNotFoundError: No module named 'nibeuplink'
```

hass_nibe: d39800d2f6f10a7a4620d8117e996ab9302ca10b
HA: 0.88.1
HassOS: 2.10

**Comment by elupus** [comment]
You have the weird issue of hassio not loading dependencies.

Do you have some earlier warning in your log?

**Comment by ChristophLindemann** [comment]
Hmm, the error is gone. Even rebooting, I do not see the error anymore. Maybe something else was updated.

So I guess we should close this issue. I can not reproduce it anymore.
