### ISSUE TITLE
Error during init of new component

### ISSUE THREAD

**Issue by suelberg** [elupus/hass_nibe#23]
After updating to HA 0.89 (which was ok) the update of this component does not work out as expected:

`
2019-03-07 18:43:57 ERROR (MainThread) [homeassistant.setup] Error during setup of component nibe
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/setup.py", line 151, in _async_setup_component
    hass, processed_config)
  File "/home/homeassistant/.homeassistant/custom_components/nibe/__init__.py", line 186, in async_setup
    await async_register_services(hass)
  File "/home/homeassistant/.homeassistant/custom_components/nibe/__init__.py", line 128, in async_register_services
    from nibeuplink import SMARTHOME_MODES
  File "/srv/homeassistant/lib/python3.5/site-packages/nibeuplink/__init__.py", line 37

    name: str = attr.ib()

        ^

SyntaxError: invalid syntax
`
HASS: 0.89
NIBEUPLINK: 0.6.0.

Any suggestions? Thanks!

**Comment by elupus** [comment]
Crap. Python 3.5 strikes again. That works on 3.6.

**Comment by suelberg** [comment]
Uhh. That's a bummer. I am a little hesitant to update the python on that little raspberry... it is 3.5.3 what is installed there (it used to be a standard raspbian or hasbian I believe). Any chance you have a quick fix available or will I need to do some surgery on the box? Thanks for looking into this so quickly! 

Actually downgrading to your older version worked without problems so personally I have no need for a fix in the close future.

Besides that: Integrating my Nibe 1255 into the rest of the house is by far the coolest integration of all. **Thank you so much for your work!**

**Comment by elupus** [comment]
I think i've got this fixed. Give it a try with new version.
