### ISSUE TITLE
Unable to start Homeassistant while "nibe:" is in configuration.yaml

### ISSUE THREAD

**Issue by iCarl** [elupus/hass_nibe#37]
I am unable to start Homeassistant while "nibe:" is in configuration.yaml.
I just made a fresh virtualenv install off Homeassistant 0.93.1 running on a Raspberry pi 3B.

```
/usr/lib/python3.5/asyncio/base_events.py:491: RuntimeWarning: coroutine 'TCPConnector._resolve_host' was never awaited
  self._ready.clear()
Traceback (most recent call last):
  File "/srv/homeassistant/bin/hass", line 11, in <module>
    sys.exit(main())
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/__main__.py", line 396, in main
2019-05-19 10:19:10 ERROR (Thread-17) [concurrent.futures] exception calling callback for <Future at 0x693d5e30 state=finished returned dict>
Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 297, in _invoke_callbacks
    callback(self)
  File "/usr/lib/python3.5/asyncio/futures.py", line 463, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 618, in call_soon_threadsafe
    self._check_closed()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 357, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2019-05-19 10:19:10 ERROR (Thread-5) [concurrent.futures] exception calling callback for <Future at 0x686fc990 state=finished returned dict>
Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 297, in _invoke_callbacks
    callback(self)
  File "/usr/lib/python3.5/asyncio/futures.py", line 463, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 618, in call_soon_threadsafe
    self._check_closed()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 357, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
    exit_code = asyncio_run(setup_and_run_hass(config_dir, args))
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/util/async_.py", line 29, in asyncio_run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 466, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/__main__.py", line 290, in setup_and_run_hass
    log_no_color=args.log_no_color)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/bootstrap.py", line 181, in async_from_config_file
    config_dict, hass, enable_log=False, skip_pip=skip_pip)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/bootstrap.py", line 92, in async_from_config_dict
    await _async_set_up_integrations(hass, config)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/bootstrap.py", line 404, in _async_set_up_integrations
    for domain in domains_to_load
  File "/usr/lib/python3.5/asyncio/futures.py", line 380, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 304, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/setup.py", line 50, in async_setup_component
    return await task  # type: ignore
  File "/usr/lib/python3.5/asyncio/futures.py", line 380, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 304, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/setup.py", line 126, in _async_setup_component
    hass, config, integration)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/config.py", line 773, in async_process_component_config
    component = integration.get_component()
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/loader.py", line 130, in get_component
    cache[self.domain] = importlib.import_module(self.pkg_path)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/homeassistant/.homeassistant/custom_components/nibe/__init__.py", line 15, in <module>
    from nibeuplink import Uplink
  File "/srv/homeassistant/lib/python3.5/site-packages/nibeuplink/__init__.py", line 25, in <module>
    from .monitor import Monitor
  File "/srv/homeassistant/lib/python3.5/site-packages/nibeuplink/monitor.py", line 8, in <module>
    from .utils import cyclic_tuple
  File "/srv/homeassistant/lib/python3.5/site-packages/nibeuplink/utils.py", line 3, in <module>
    from typing import Iterable, Tuple, Any, Deque
ImportError: cannot import name 'Deque'

```

Any idea what this could be?
I also tried the monitor branch, and I can see the Nibe Uplink integration in the list, but I am unable to add it.

**Comment by elupus** [comment]
Argh.. stupid python 3.5. Don't use monitor branch. What do you get with master?

**Comment by iCarl** [comment]
The message above is from the master branch

**Comment by elupus** [comment]
Oh right. It still imports that. Well I need to figure out some silly workaround for python 3.5 again. Can't wait for HA to require 3.6

**Comment by elupus** [comment]
Please update. Hopefully fixed.

**Comment by iCarl** [comment]
It seems to be working!
Although I cant get the fan component to work

**Comment by elupus** [comment]
Open a new issue on the fan stuff.
