### ISSUE TITLE
Unknown error occured

### ISSUE THREAD

**Issue by weenerberg** [elupus/hass_nibe#42]
Following the README.md to setup the hass_nibe component with _latest_ as per today.
When filling in the identifier, secret, callback etc I get an "Unknow error occured".
Get this stacktrace in the log:

  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 119, in impl,
2019-06-23 02:20:46 ERROR (MainThread) [aiohttp.server] Error handling request,
Traceback (most recent call last):,
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start,
    resp = await task,
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle,
    resp = await handler(request),
    return await handler(request),
  File "/usr/src/app/homeassistant/components/http/real_ip.py", line 33, in real_ip_middleware,
  File "/usr/src/app/homeassistant/components/http/ban.py", line 68, in ban_middleware,
  File "/usr/src/app/homeassistant/components/http/auth.py", line 216, in auth_middleware,
  File "/usr/src/app/homeassistant/components/http/view.py", line 115, in handle,
    result = await result,
  File "/usr/src/app/homeassistant/components/config/config_entries.py", line 154, in post,
    return await super().post(request, flow_id),
  File "/usr/src/app/homeassistant/components/http/data_validator.py", line 46, in wrapper,
    result = await method(view, request, *args, **kwargs),
  File "/usr/src/app/homeassistant/helpers/data_entry_flow.py", line 86, in post,
    result = await self._flow_mgr.async_configure(flow_id, data),
  File "/usr/src/app/homeassistant/data_entry_flow.py", line 80, in async_configure,
    flow, step_id, user_input),
  File "/usr/src/app/homeassistant/data_entry_flow.py", line 98, in _async_handle_step,
    result = await getattr(flow, method)(user_input)  # type: Dict,
  File "/config/custom_components/nibe/config_flow.py", line 51, in async_step_user,
    return await self.async_step_auth(),
  File "/config/custom_components/nibe/config_flow.py", line 102, in async_step_auth,
    return self.async_external_step(,
AttributeError: 'NibeConfigFlow' object has no attribute 'async_external_step'

**Comment by elupus** [comment]
Your Homer assistans need to be updated

**Comment by weenerberg** [comment]
Upgraded HA to version 0.94.4. That did the trick.
Thank you!
