### ISSUE TITLE
Hass 0.69.1 - Future exception was never retrieved

### ISSUE THREAD

**Issue by magnushasselquist** [elupus/hass_nibe#6]
Was this something new in 0.69.1 ? Suddenly my HASS cannot load NIBE..

Future exception was never retrieved

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/cmj/.homeassistant/custom_components/nibe.py", line 181, in update_systems
    for system in systems['objects'] if str(system['systemId']) in configs
  File "/Users/cmj/.homeassistant/custom_components/nibe.py", line 181, in <dictcomp>
    for system in systems['objects'] if str(system['systemId']) in configs
  File "/Users/cmj/.homeassistant/custom_components/nibe.py", line 225, in __init__
    group = loader.get_component('group')
TypeError: get_component() missing 1 required positional argument: 'comp_or_platform'

**Comment by davle** [comment]
I have the same problem after updating.

**Comment by elupus** [comment]
resolved in latest version of module branch.

**Comment by bratanon** [comment]
This is still a problem is 0.70.1

**Comment by elupus** [comment]
Not in the module branch. Master is deprecated. Suppose I should remove it.

**Comment by bratanon** [comment]
well, master should be the default if you ask me.
