### ISSUE TITLE
nibe 

### ISSUE THREAD

**Issue by PaleSkinnySwede** [elupus/hass_nibe#69]
I just tried the manual installation on my HA. I came to the bit where I should add `nibe:` to my `configuration.yaml` file. When I checked the configuration it threw the following error:
```
Component error: nibe - Integration 'nibe' not found.
```

My `custom_components` folder is in the same folder as my `configuration.yaml` file.

Ideas?

**Comment by PaleSkinnySwede** [comment]
From the home-assistant.log:

```
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/homeassistant/.homeassistant/custom_components/nibe/__init__.py", line 14, in <module>
    from nibeuplink import Uplink, UplinkSession
ModuleNotFoundError: No module named 'nibeuplink'
2020-05-27 15:56:52 ERROR (MainThread) [homeassistant.components.homeassistant] Component error: nibe - Integration 'nibe' not found.```

**Comment by elupus** [comment]
Just strange. It should have installed nibeuplink automatically. It's listed as a dependency.

No errors earlier in your log?

**Comment by PaleSkinnySwede** [comment]
Here's the whole log:
```
2020-05-27 15:35:34 ERROR (MainThread) [homeassistant.setup] Setup failed for nibe: Integration not found.
2020-05-27 15:48:45 ERROR (MainThread) [homeassistant.loader] Error loading custom_components.nibe. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/loader.py", line 387, in _load_file
    module = importlib.import_module(path)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/homeassistant/.homeassistant/custom_components/nibe/__init__.py", line 14, in <module>
    from nibeuplink import Uplink, UplinkSession
ModuleNotFoundError: No module named 'nibeuplink'
2020-05-27 15:56:52 ERROR (MainThread) [homeassistant.loader] Error loading custom_components.nibe. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/loader.py", line 387, in _load_file
    module = importlib.import_module(path)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/homeassistant/.homeassistant/custom_components/nibe/__init__.py", line 14, in <module>
    from nibeuplink import Uplink, UplinkSession
ModuleNotFoundError: No module named 'nibeuplink'
2020-05-27 15:56:52 ERROR (MainThread) [homeassistant.components.homeassistant] Component error: nibe - Integration 'nibe' not found.
```

**Comment by elupus** [comment]
Not whole log. Stuff occured before that

**Comment by PaleSkinnySwede** [comment]
Then something else is broken. That's the whole `home-assistant.log` file. It's 2437 bytes and I used `less` to display the whole thing.

I'll remove everything and will try again.

**Comment by elupus** [comment]
Ok. You may need to enable debug logging on homeassistant.

**Comment by PaleSkinnySwede** [comment]
I'm running vanilla HA on Raspian.

This is all a get when turning on debug logging and restarting the system:

```
2020-05-27 16:29:53 ERROR (MainThread) [homeassistant.loader] Error loading custom_components.nibe. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/loader.py", line 387, in _load_file
    module = importlib.import_module(path)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/homeassistant/.homeassistant/custom_components/nibe/__init__.py", line 14, in <module>
    from nibeuplink import Uplink, UplinkSession
ModuleNotFoundError: No module named 'nibeuplink'
2020-05-27 16:29:53 ERROR (MainThread) [homeassistant.components.homeassistant] Component error: nibe - Integration 'nibe' not found.
```

The component is in `/home/homeassistant/.homeassistant/custom_components/nibe/` and I've checked all the ownerships of the folders and files too.

Which dependency am I missing, and can I install it manually?

**Comment by elupus** [comment]
Inside venv I hope? Otherwise that is your problem.

**Comment by PaleSkinnySwede** [comment]
Yes, inside venv.

**Comment by elupus** [comment]
You need to get debug logging turned on.you should be getting a lot more logs from other components of home assistant.

**Comment by PaleSkinnySwede** [comment]
I get a lot of logs coming in, but nothing related to the nibe component.
What should I search for in the log file?

**Comment by PaleSkinnySwede** [comment]
I manually installed `nibeuplink` using `pip3 install nibeuplink` and that took me one step further. I still can't find Nibe Uplink as an Integration though... I'll continue later tonight.

Appreciate that you've taken the time so far. Thanks!

**Comment by elupus** [comment]
I wonder. You are note missing the manifest.json file in the installed folder?

**Comment by PaleSkinnySwede** [comment]
Nope. It's there:
```
homeassistant@homeassistant:~/.homeassistant/custom_components/nibe $ ls -la
total 152
drwxr-xr-x 6 homeassistant homeassistant  4096 May 27 16:29 .
drwxr-xr-x 3 homeassistant homeassistant  4096 May 27 16:28 ..
-rw-r--r-- 1 homeassistant homeassistant  1425 May 23 11:37 binary_sensor.py
-rw-r--r-- 1 homeassistant homeassistant 21939 May 23 11:37 climate.py
-rw-r--r-- 1 homeassistant homeassistant  6241 May 23 11:37 config_flow.py
-rw-r--r-- 1 homeassistant homeassistant  1300 May 23 11:37 const.py
drwxr-xr-x 2 homeassistant homeassistant  4096 May 23 11:37 docs
-rw-r--r-- 1 homeassistant homeassistant  8532 May 23 11:37 entity.py
-rw-r--r-- 1 homeassistant homeassistant  4925 May 23 11:37 fan.py
-rw-r--r-- 1 homeassistant homeassistant    40 May 23 11:37 .gitignore
-rw-r--r-- 1 homeassistant homeassistant   201 May 23 11:37 hacs.json
-rw-r--r-- 1 homeassistant homeassistant 10031 May 23 11:37 __init__.py
-rw-r--r-- 1 homeassistant homeassistant   226 May 23 11:37 manifest.json
drwxr-xr-x 2 homeassistant homeassistant  4096 May 27 16:59 __pycache__
-rw-r--r-- 1 homeassistant homeassistant  4654 May 23 11:37 README.md
-rw-r--r-- 1 homeassistant homeassistant  3363 May 23 11:37 sensor.py
-rw-r--r-- 1 homeassistant homeassistant  4516 May 23 11:37 services.py
-rw-r--r-- 1 homeassistant homeassistant  1769 May 23 11:37 services.yaml
-rw-r--r-- 1 homeassistant homeassistant   345 May 23 11:37 setup.cfg
-rw-r--r-- 1 homeassistant homeassistant  1566 May 23 11:37 strings.json
-rw-r--r-- 1 homeassistant homeassistant  1651 May 23 11:37 switch.py
drwxr-xr-x 2 homeassistant homeassistant  4096 May 23 11:37 translations
drwxr-xr-x 2 homeassistant homeassistant  4096 May 23 11:37 .vscode
-rw-r--r-- 1 homeassistant homeassistant  8002 May 23 11:37 water_heater.py
```

**Comment by PaleSkinnySwede** [comment]
It started to work now. I have no idea why. Haven't touched it during the past 5 hours. Thanks for your engagement!

**Comment by Casenl** [comment]
Just wanted to add that I had the exact same problem, and using pip3 install nibeuplink from the docker terminal did the trick.
