### ISSUE TITLE
Task exception was never retrieved

### ISSUE THREAD

**Issue by labbs1** [elupus/hass_nibe#76]
Hi, I recently added this integration and it works fine.
Although it triggers a lot of the following log entries every minute.

Could it be something I did wrong?

`Logger: homeassistant
Source: custom_components/nibe/__init__.py:328
First occurred: 13:34:19 (6 occurrences)
Last logged: 13:39:19

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/nibe/services.py", line 44, in fun
    await callable()
  File "/config/custom_components/nibe/__init__.py", line 328, in update_notifications
    notice = await self.uplink.get_notifications(self.system_id)
  File "/usr/local/lib/python3.8/site-packages/nibeuplink/uplink.py", line 253, in get_notifications
    data = await self.get(f"systems/{system_id}/notifications", params=params)
  File "/usr/local/lib/python3.8/site-packages/nibeuplink/uplink.py", line 73, in get
    return await self.session.request(
  File "/usr/local/lib/python3.8/site-packages/nibeuplink/session.py", line 168, in request
    response = await self.session.request(*args, auth=await self._get_auth(), **kw)
AttributeError: 'NoneType' object has no attribute 'request'`

**Comment by elupus** [comment]
How are you running home assistant and how did you install the component?

Seems you have an old version of nibeuplink installed in /usr/local...

**Comment by labbs1** [comment]
I'm running HA on Pi4 but installed Niba manually in June. Removed it now and installed it with HACS but cannot get it running since trying to add the integration halts. Might be doing something wrong but I am not that good troubleshooting this code.

The error I get now is:

Logger: aiohttp.server
Source: custom_components/nibe/config_flow.py:68
First occurred: 17:14:17 (1 occurrences)
Last logged: 17:14:17

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 18, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 72, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 127, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 129, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 136, in post
    return await super().post(request)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 60, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 69, in post
    result = await self._flow_mgr.async_init(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 128, in async_init
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 201, in _async_handle_step
    result: Dict = await getattr(flow, method)(user_input)
  File "/config/custom_components/nibe/config_flow.py", line 68, in async_step_user
    config = self.hass.data[DATA_NIBE].config
KeyError: 'nibe'

Thanks!

**Comment by elupus** [comment]
I thought I had fixed that.. do you have an empty nibe section in config?

**Comment by labbs1** [comment]
Yes, I removed all nibe: settings I had

**Comment by elupus** [comment]
Make sure there still is a section like:
```
nibe:
```

**Comment by labbs1** [comment]
Just did, and  got 2 units (Climate System S1 and my PumpId) along with 4 enteties. Previously I had 1 unit and 45 enteties.

**Comment by elupus** [comment]
That is expected. You can turn on categories data again from the config. Check readme.

**Comment by labbs1** [comment]
So I did and got 8 units and 45 enteties again  ;)
Tack för hjälpen!

**Comment by labbs1** [comment]
One last question, is there any option in the API to get notification regarding updates?

**Comment by elupus** [comment]
What updates? You mean pump firmware? No, it's not part of the API as far as I can see.

**Comment by labbs1** [comment]
Yes, understand. Thanks again!
